title: Daily Insights
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  A daily collection of trends and insights.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kamajyna.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# theme: minima
lang: ko
timezone: Asia/Seoul

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
google_analytics: G-WJH817N0CD
google_adsense: "ca-pub-9692425694108429"

